# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Basic Concepts Of Fixed Income: Basic Bond Concepts and the Term Structure of Interest Rates"
author: Financial Python
copyright: "2025 by the University of Virginia Darden School Foundation, Charlottesville, VA." # This will appear in the footer
logo: 

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PatrickJHess/Vol-3-Chap-1  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository



launch_buttons:
  thebe: true
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"

html:
  baseurl: "https://patrickjhess.github.io/Vol-3-Chap-1/"
  use_issues_button: true

sphinx:
  extra_extensions:
    - sphinx_design
    - sphinx_sitemap
  config:
    # This must point to the Chapter URL
    html_baseurl: "https://patrickjhess.github.io/Vol-3-Chap-1/"
    sitemap_url_scheme: "{link}"
    html_static_path: ['_static']
    html_js_files:
      # The 'priority: 200' helps move this script above the Thebe injection
      - ['open_new_tab.js', {priority: 200}]
    html_css_files:
      - custom.css
    html_extra_path:
      - google6c5f2d11d0c13eff.html   
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    thebe_config:
      selector: ".thebe,.cell"
      repository_url: "https://github.com/patrickjhess/Vol-3-Chap-1"
      repository_branch: "master"

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
